# Generated by Django 6.0.2 on 2026-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='ID')),
            ],
        ),
    ]
