# Generated by Django 6.0.2 on 2026-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='ID'),
        ),
    ]
