# Generated by Django 6.0.2 on 2026-03-13 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AddConstraint(
            model_name='eventmembership',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_membership'),
        ),
    ]
