# Generated by Django 6.0.2 on 2026-03-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_join_request')],
            },
        ),
    ]
