# Generated by Django 6.0.2 on 2026-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventjoinrequest'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participants',
            constraint=models.UniqueConstraint(fields=('full_name', 'event'), name='unique_user_event_Participants'),
        ),
    ]
