# Generated by Django 6.0.2 on 2026-03-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_participants_unique_user_event_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenses', verbose_name='expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.participants', verbose_name='participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'expense'), name='unique_participant_expense')],
            },
        ),
    ]
