# Generated by Django 6.0.2 on 2026-03-20 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_splitpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
    ]
