# Generated by Django 6.0.2 on 2026-03-21 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_splitpayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='expenses.expenses', verbose_name='expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='expenses.participants', verbose_name='participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'expense'), name='unique_participant_expense_for_expense_payment_model')],
            },
        ),
    ]
