# Generated by Django 6.0.2 on 2026-03-23 18:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paid amount'),
        ),
        migrations.AddField(
            model_name='participants',
            name='total_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Share amount'),
        ),
    ]
