# Generated by Django 6.0.2 on 2026-03-23 19:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_participants_total_paid_participants_total_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total cost'),
        ),
    ]
