# Generated by Django 6.0.2 on 2026-03-24 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_expenses_total_cost_expenses_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paid amount')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Share amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='expensepayment',
            name='unique_participant_expense_for_expense_payment_model',
        ),
        migrations.RemoveConstraint(
            model_name='splitpayment',
            name='unique_participant_expense',
        ),
        migrations.AddField(
            model_name='participantexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenses', verbose_name='expense'),
        ),
        migrations.AddField(
            model_name='participantexpense',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.participants', verbose_name='participant'),
        ),
        migrations.RemoveField(
            model_name='expensepayment',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensepayment',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='splitpayment',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='splitpayment',
            name='participant',
        ),
        migrations.AddConstraint(
            model_name='participantexpense',
            constraint=models.UniqueConstraint(fields=('participant', 'expense'), name='unique_participant_expense'),
        ),
        migrations.DeleteModel(
            name='ExpensePayment',
        ),
        migrations.DeleteModel(
            name='SplitPayment',
        ),
    ]
