# Generated by Django 6.0.2 on 2026-03-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventjoinrequest'),
        ('expenses', '0009_participantexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencys', to='events.event', verbose_name='event')),
            ],
        ),
    ]
